name: nextServerlessDemo

nextServerlessDemo:
  component: "@sls-next/serverless-component@3.5.2"
  inputs:
    name:
      defaultLambda: nextSlsDefaultLambda
      apiLambda: nextSlsApiLambda
      imageLambda: nextSlsImageLambda
    memory:
      defaultLambda: 1024
      apiLambda: 512
      imageLambda: 512
    publicDirectoryCache:
      value: public, max-age=604800
      test: /\.(gif|jpe?g|png|txt|xml)$/i